language: node_js
node_js:
- 7
- 8
- 10
cache:
- node_modules
before_install:
- npm install -g npm
script:
- npm install
- npm run package.json
deploy:
  provider: heroku
  api_key:
    secure: R2B+G/ZctOw15eicvtNpgVP0PXhKI/fLq5wTPxEwDjVzzwbTj3xeZmf4Uv3abEaafOny4g/4jSNu3utvBUJGoaXc6Zz1GlPLNUeQ/vMxYABsHyy4yCpje4SlJu+GYbBjJy18iem+p0tWpYw65IjfR1e1ziALHO6kD0TBuVcmfPgB/Rg710K/eC4+VQytFt3dsZlhUDz9NxgjGnJa4O/T3No9jed/juiLFdp5DI1DHUxMLA0j8Ow1cMupXlcxKt5nNnE6e4KV36w6widNh1JyKCc8fxYTTBG2uj81e5BVnWtDQtqNs5PsZAg65HxN1IUlnpuamWTtOmPsnlo+t1lCdsPSjWTzHIv5pQnRQ6LDBi61SrArrjJTob0epVlJRTBSb/aoqnaXWzCdVNJSYOc5MAFT+2AalxEEe0g05Owtc4F3T/AorBzjBkMuzHrcyo/fMxiRsUreej+iYYqd4Nr59r09M4mL11VAr4FF0oowk0UtKHrs1wL35HjyVyEMTTrs2H09cj4PXVX7iBOtIbk6xW5U8ewLSI2HD2Lslzn9DUYXUu4MEoeW2Pn5PDMwhbX21Fe/1QTsNOgErwmLoGQCpfX2jrqMh7jayCzH2UiRY4qMCc1YukUQ0VDrB9Q8voPj4XI2gy/dCgzKpR4QmeKdehaNqjWwykohuehr6fUJdT4=
  app: rachenn
  on:
    repo: rachenn/rachenn.com
