language: node_js
node_js:
- 7
- 8
- 10
cache:
- node_modules
before_install:
- npm install -g npm
script:
- npm install
- npm run pretest
deploy:
  provider: heroku
  api_key:
    secure: slK0Lqf5xUtB39I7Y/DdtM0LROi5W42yO/p4EKXCybtvwRIC7Ip0M3M9n15zfjfD+8jSAoy63dyzRW2GWkmxXVIP+tGl2zjUD0PgGWW1u8Vm9NzycHh8Rp9c22I0uzvFQzZwr8rx4+GnYxF/b23MUqaJ6DeZbpZUO0MXOPPqvnM1E32b1fGkukiZ/Qs+yLxKmx0Z3MHJthTHrGUaIr7px9ZF0Me7XLQaoKHnNIOaMuruskEUb3XBSTEHZE2SHgtNI9ZoeOb9WLQZv+O50ptxXhYvAiuHwxEOe7qNk+GqewiUPwmt1ZfdW/3Ylegz86TNbN+ienBlfWLcyucD/l+7nU09EZsoKS5LCxrutiyOBcVBQpbSGrY4h/6LUvTtJyYJqzcvK0PH+tB4KmC5HUNaazb69ohy62kSedk/AcQCHjjDZYEtZnsKv5RCvKZyW1mcZcUMWizM0A0JD3pnFA/BflZ0WyPj0+mTIfxiyrzCaNlnf8y82Dh2dnqjrsUABN/5KcdY2oqX6xYWMEGV5DVwGPQz5H2Pv9trsas61BjnYIytBJm2fs4HDZ7zdDfmIu0ZjoImBMdCa3Qg7QL7xi7FfbmKUmlLS1bSYhF3IwLPCRBHxXMmhmwNuekMEBGxIaR7kJgKy3Ji1vsHhJID9d83e1LKfNqH7nX5YUyx6ixhcKM=
  app: rachenn
  on:
    repo: rachenn/rachenn.com